client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    # path('', views.index, name='index'),
    path('list/', views.ClientListView.as_view(), name='client_list'),
    path('detail/<int:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('create/', views.ClientCreateView.as_view(), name='client_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('create_visit/<int:pk>/', views.create_visit, name='create_visit'),
    path('update/<int:pk>/', views.ClientUpdateView.as_view(), name='client_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('update_visit/<int:pk>/', views.update_visit, name='update_visit'),
    path('delete/<int:pk>/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
    path('delete_visit/<int:pk>/', views.delete_visit, name='delete_visit'),
]

cost/urls.py
from django.urls import path
from . import views


app_name = 'cost'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.CostListView.as_view(), name='cost_list'),
    path('create/', views.CostCreateView.as_view(), name='cost_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.CostUpdateView.as_view(), name='cost_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.CostDeleteView.as_view(), name='cost_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
]

kaikei/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('cost/', include('cost.urls')),
    path('sales/', include('sales.urls')),
    path('client/', include('client.urls')),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime


class Client(models.Model):
    class Meta:
        db_table ="client"
        verbose_name ="顧客"
        verbose_name_plural ="顧客"

    client_name = models.CharField(verbose_name="顧客名", max_length=255)
    receipt_name = models.TextField(verbose_name="領収書宛名", max_length=1000, blank=True)
    tel_number = models.CharField(verbose_name='電話番号', max_length=15, blank=True, help_text="任意 (例: 09012345678)")
    memo = models.TextField(verbose_name="備考", max_length=1000, blank=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="ユーザー")

    def __str__(self):
        return '{0}'.format(self.client_name)


class Visit(models.Model):
    class Meta:
        db_table ="visit"
        verbose_name ="来店記録"
        verbose_name_plural ="来店記録"

    client = models.ForeignKey(Client, related_name='visits', on_delete = models.PROTECT, verbose_name="顧客名")
    visit_date = models.DateField(verbose_name="来店日",default=datetime.now)
    menu = models.TextField(verbose_name="メニュー", max_length=1000, blank=True)
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return '{0} {1} {2}'.format(self.client, self.visit_date, self.menu)

client/forms.py
from django import forms
from .models import Client, Visit


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['client_name', 'receipt_name', 'tel_number', 'memo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs['placeholder'] = field.label


class VisitCreateForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ('visit_date', 'menu')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs['placeholder'] = field.label

client/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.views.generic import TemplateView
from .forms import ClientForm, VisitCreateForm
from .models import Client, Visit


class ClientListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Client
    template_name = 'client/client_list.html'

    def queryset(self):
        return Client.objects.filter(author=self.request.user).order_by('-pk')


class ClientDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Client
    template_name = 'client/client_detail.html'


class ClientCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:create_done')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(ClientCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        client_name_list = []
        context = super().get_context_data(**kwargs)
        client_data = Client.objects.filter(author=self.request.user)
        for client in client_data:
            client_name_list.append(client.client_name)
        context["client_name_list"] = client_name_list
        return context

@login_required
def create_done(request):
    return render(request, 'client/create_done.html')


@login_required
def create_visit(request, pk):
    if request.method == 'POST':
        form = VisitCreateForm(request.POST)
        if form.is_valid():
            visit = form.save(commit=False)
            visit.client = get_object_or_404(Client, pk=pk)
            visit.save()
            return redirect('client:client_detail', pk=pk)
    else:
        form = VisitCreateForm()
    context = {
        'form': form,
    }
    return render(request, 'client/client_visit_form.html', context)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:update_done')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(ClientUpdateView, self).form_valid(form)

@login_required
def update_done(request):
    return render(request, 'client/update_done.html')


@login_required
def update_visit(request, pk):
    visit = get_object_or_404(Visit, id=pk)
    if request.method == 'POST':
        form = VisitCreateForm(request.POST)
        if form.is_valid():
            visit.visit_date = form.cleaned_data['visit_date']
            visit.menu = form.cleaned_data['menu']
            visit.save()
            return redirect('client:client_detail', pk=visit.client.id)
    else:
        form = VisitCreateForm({
            'visit_date': visit.visit_date,
            'menu': visit.menu,
        })
    context = {
        'form': form,
    }
    return render(request, 'client/client_visit_form.html', context)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Client
    success_url = reverse_lazy('client:delete_done')

@login_required
def delete_done(request):
    return render(request, 'client/delete_done.html')


@login_required
def delete_visit(request, pk):
    visit = get_object_or_404(Visit, id=pk)
    if request.method == 'POST':
        visit.delete()
        return redirect('client:client_detail', pk=visit.client.id)
    else:
        context = {
            'visit': visit,
        }
        return render(request, 'client/client_visit_confirm_delete.html', context)

client/templates/client/client_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/done.css' %}">
<link rel="stylesheet" href="{% static 'css/client/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-exclamation-triangle"></i>削除確認</h3>
        <p>{{ object }} のデータを削除していいですか？</p>
        <form method="post">
            <button class="confirm_btn">削除する</button>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

client/templates/client/client_detail.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/client_detail.css' %}">
<link rel="stylesheet" href="{% static 'css/client/client_detail_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="rireki_contents">
    <h1 class="clientList_title">{{ client.client_name }}様の来店日・メニューリスト<h1>
    <table id=table_list>
        <thead>
            <tr>
                <th>ID <i class="fas fa-sort"></i></th>
                <th>来店日 <i class="fas fa-sort"></i></th>
                <th>メニュー <i class="fas fa-sort"></i></th>
                <th>更新・削除</th>
            </tr>
        </thead>
        <tbody>
        {% for visit in client.visits.all %}
            <tr class="odd gradeX text-center">
                <td>{{ visit.id}}</td>
                <td>{{ visit.visit_date }}</td>
                <td>{{ visit.menu | linebreaksbr}}</td>
                <td>
                    <a class="update_btn" href="{% url 'client:update_visit' visit.pk %}">更新</a>
                    <a class="delete_btn" href="{% url 'client:delete_visit' visit.pk %}">削除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="new_btn">
    <a class="new_btn_link" href="{% url 'client:create_visit' client.pk %}"><i class="fas fa-fish new_icon"></i></a>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
{% endblock %}
{% block script %}
<script>
    jQuery(function($){
        $.extend( $.fn.dataTable.defaults, {
            language: {
                    url: "https://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
                }
        });
        $("#table_list").DataTable({
            "searching": true,
            "paging":   true,
            "ordering": true,
            "lengthChange": true,
            "pageLength": 25,
            "order": [[ 0, "desc" ]],
        }).columns.adjust().draw();
    });
</script>
{% endblock %}

client/templates/client/client_form.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/client_form.css' %}">
{% endblock %}
{% block content %}
<div class="form_contents">
    <h1 class="form_title">顧客情報入力</h1>
    <form action="" method="POST">
        {{ form.non_field_errors }}
        <div class="field">
            <p>{{ form.client_name.label }}</p>
            {{ form.client_name }}
            <div class="js-suggestions"></div>
            {{ form.client_name.errors }}
        </div>
        <div class="field">
            <p>{{ form.receipt_name.label }}(任意)</p>
            {{ form.receipt_name }}
            {{ form.receipt_name.errors }}
        </div>
        <div class="field">
            <p>{{ form.tel_number.label }}(任意)</p>
            {{ form.tel_number }}
            {{ form.tel_number.errors }}
        </div>
        <div class="field">
            <p>{{ form.memo.label }}(任意)</p>
            {{ form.memo }}
            {{ form.memo.errors }}
        </div>
        <div class="field submit_btn">
            <button type="submit">送信</button>
        </div>
        {% csrf_token %}
    </form>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
<script>
    const list = [
        {% for name in client_name_list %}
            "{{name}}",
        {% endfor %}
    ];
    const elInput = document.querySelector("#id_client_name");
    const elSuggestions = document.querySelector(".js-suggestions");
    const state = {
        inputValue: elInput.value,
        inputting: false
    };
    const dataMap = new WeakMap();

    function render() {
        renderInput();
        renderSuggestions();
    }

    function renderInput() {
        elInput.value = state.inputValue;
    }

    function renderSuggestions() {
        const elNewList = document.createElement("ul");
        if (state.inputting) {
            list.filter(text => text.includes(state.inputValue)).forEach(text => {
            const elItem = document.createElement("li");
            dataMap.set(elItem, { text });
            elItem.textContent = text;
            elItem.addEventListener("click", handleClickItem);
            elNewList.appendChild(elItem);
            });
        }
        elSuggestions.innerHTML = "";
        elSuggestions.appendChild(elNewList);
    }

    function handleClickItem(e) {
        state.inputValue = dataMap.get(e.currentTarget).text;
        state.inputting = false;

        render();
    }

    elInput.addEventListener("input", () => {
        state.inputValue = elInput.value;
        state.inputting = elInput.value !== "";

        renderSuggestions();
    });
</script>
{% endblock %}

client/templates/client/client_list.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/client_list.css' %}">
<link rel="stylesheet" href="{% static 'css/client/client_list_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="rireki_contents">
    <h1 class="clientList_title">顧客リスト<h1>
    <table id=table_list>
        <thead>
            <tr>
                <th>ID <i class="fas fa-sort"></i></th>
                <th>顧客名 <i class="fas fa-sort"></i></th>
                <th>領収書宛名 <i class="fas fa-sort"></i></th>
                <th>連絡先 <i class="fas fa-sort"></i></th>
                <th>備考 <i class="fas fa-sort"></i></th>
                <th>来店日・メニュー</th>
                <th>更新・削除</th>
            </tr>
        </thead>
        <tbody>
        {% for client in object_list %}
            <tr class="odd gradeX text-center">
                <td>{{ client.id}}</td>
                <td>{{ client.client_name }}様</td>
                <td>{{ client.receipt_name | linebreaksbr }}</td>
                <td>{{ client.tel_number }}</td>
                <td>{{ client.memo | linebreaksbr }}</td>
                <td><a class="detail_btn" href="{% url 'client:client_detail' client.pk %}">来店日・メニュー</a></td>
                <td>
                    <a class="update_btn" href="{% url 'client:client_update' client.pk %}">更新</a>
                    <a class="delete_btn" href="{% url 'client:client_delete' client.pk %}">削除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="new_btn">
    <a class="new_btn_link" href="{% url 'client:client_create' %}"><i class="fas fa-user-alt new_icon"></i></a>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
{% endblock %}
{% block script %}
<script>
    jQuery(function($){
        $.extend( $.fn.dataTable.defaults, {
            language: {
                    url: "https://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
                }
        });
        $("#table_list").DataTable({
            "searching": true,
            "paging":   false,
            "ordering": true,
            "lengthChange": false,
            "order": [[ 0, "desc" ]],
        }).columns.adjust().draw();
    });
</script>
{% endblock %}

client/templates/client/client_visit_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/done.css' %}">
<link rel="stylesheet" href="{% static 'css/client/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-exclamation-triangle"></i>削除確認</h3>
        <p>{{ visit }} のデータを削除していいですか？</p>
        <form method="post" action="{% url 'client:delete_visit' visit.pk %}">
            <button class="confirm_btn">削除する</button>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

client/templates/client/client_visit_form.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/client_visit_form.css' %}">
<link rel="stylesheet" href="https://fengyuanchen.github.io/datepicker/css/datepicker.css">
{% endblock %}
{% block content %}
<div class="form_contents">
    <h1 class="form_title">来店日・メニュー情報入力</h1>
    <form action="" method="POST">
        {{ form.non_field_errors }}
        <div class="field">
            <p>{{ form.visit_date.label }}</p>
            {{ form.visit_date }}
            {{ form.visit_date.errors }}
        </div>
        <div class="field">
            <p>{{ form.menu.label }}(任意)</p>
            {{ form.menu }}
            {{ form.menu.errors }}
        </div>
        <div class="field submit_btn">
            <button type="submit">送信</button>
        </div>
        {% csrf_token %}
    </form>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://fengyuanchen.github.io/datepicker/js/datepicker.js"></script>
<script src="https://fengyuanchen.github.io/datepicker/js/datepicker.ja-JP.js"></script>
{% endblock %}
{% block script %}
<script>
    $('#id_visit_date').datepicker({
        format: 'yyyy-mm-dd',
        // language: 'ja-JP',
    });
</script>
{% endblock %}

client/templates/client/create_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/done.css' %}">
<link rel="stylesheet" href="{% static 'css/client/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-server"></i>登録完了</h3>
        <p><i class="fas fa-check-double"></i>データ登録が正常終了しました。</p>
        <a href="{% url 'client:client_create' %}">もう一度入力</a><a href="{% url 'client:client_list' %}">顧客一覧</a>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

client/templates/client/delete_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/done.css' %}">
<link rel="stylesheet" href="{% static 'css/client/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-server"></i>削除完了</h3>
        <p><i class="fas fa-check-double"></i>データ削除が正常終了しました。</p>
        <a href="{% url 'client:client_list' %}">履歴一覧へ</a>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

client/templates/client/update_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/client/done.css' %}">
<link rel="stylesheet" href="{% static 'css/client/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-server"></i>更新完了</h3>
        <p><i class="fas fa-check-double"></i>データ更新が正常終了しました。</p>
        <a href="{% url 'client:client_list' %}">履歴一覧へ</a>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}