accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('', views.index, name='index'),
    path('payment/', views.payment, name='payment'),
    path('payment_list/', views.payment_list, name='payment_list'),
    path('excel/', views.excel, name='excel'),
    path('excel_cost/', views.excel_cost, name='excel_cost'),
    path('excel_delivery/', views.excel_delivery, name='excel_delivery'),
    path('excel_sales/', views.excel_sales, name='excel_sales'),
    path('excel_rate/', views.excel_rate, name='excel_rate'),
    # path('import/', views.PostImport.as_view(), name='import'),
]

cost/urls.py
from django.urls import path
from . import views


app_name = 'cost'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.CostListView.as_view(), name='cost_list'),
    path('create/', views.CostCreateView.as_view(), name='cost_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.CostUpdateView.as_view(), name='cost_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.CostDeleteView.as_view(), name='cost_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
]

kaikei/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('cost/', include('cost.urls')),
    path('sales/', include('sales.urls')),
    path('client/', include('client.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
import csv
import io
from django import forms
from cost.models import Category, Shop, Cost
from sales.models import Sales


class CSVUploadForm(forms.Form):
    file = forms.FileField(label='CSVファイル', help_text='拡張子csvのファイルをアップロードしてください。')

    def clean_file(self):
        file = self.cleaned_data['file']

        if not file.name.endswith('.csv'):
            raise forms.ValidationError('拡張子がcsvのファイルをアップロードしてください')

        csv_file = io.TextIOWrapper(file, encoding='utf-8')
        reader = csv.reader(csv_file)

        self._instances = []
        try:
            for row in reader:
                # csv_data = Category(pk=row[0], category_name=row[1])
                # csv_data = Shop(pk=row[0], shop_name=row[1], flag=row[2], category_id=row[3])
                # csv_data = Cost(pk=row[0], date=row[1], shop_id=row[2], price=row[3], memo=row[4], author_id=row[5])
                csv_data = Sales(pk=row[0], date=row[1], total_sales=row[2], lunch_sales=row[3], drink_sales=row[4], dinner_guest=row[5], lunch_guest=row[6], author_id=row[7])
                self._instances.append(csv_data)
        except UnicodeDecodeError:
                raise forms.ValidationError('ファイルのエンコーディングや、正しいCSVファイルか確認ください。')

        return file

    def save(self):
        for csv_data in self._instances:
            csv_data.save()

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from cost.models import Category, Shop, Cost
from sales.models import Sales
from .forms import CSVUploadForm

import calendar
import csv
import datetime
import io
import openpyxl
from openpyxl.styles import Border, Side
from openpyxl.styles.fills import PatternFill

from .lib import setDateTime, setData, setGraph, setExcel


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


@login_required
def index(request):
    sales_matrix_list = []
    cost_matrix_list = []

    if 'param' in request.GET:
        param = request.GET['param']
        this_year = int(request.GET['year'])
        this_month = int(request.GET['month'])
        if param == 'previous':
            this_year, this_month = setDateTime.previousMonth(this_year, this_month)
        elif param == 'next':
            this_year, this_month = setDateTime.nextMonth(this_year, this_month)
        else:
            pass
    else:
        this_year, this_month = setDateTime.nowDate()

    previous_month, next_month = setDateTime.previousAndNextMonthCreation(this_month)
    previous_year = this_year - 1

    gain, cost, sales = setData.getGain(request, this_year, this_month)
    drink_rate = setData.getCostRate(request, this_year, this_month, "ドリンク", None)
    food_rate = setData.getCostRate(request, this_year, this_month, "食材", sales)

    sales_matrix_list = setGraph.makeLineChart(request, this_year, "売上")
    cost_matrix_list = setGraph.makeLineChart(request, this_year, "経費")

    return render(request, 'accounts/index.html',{
        'this_year': this_year,
        'this_month': this_month,
        'previous_month': previous_month,
        'next_month': next_month,
        'gain': gain,
        'food_rate': food_rate,
        'drink_rate': drink_rate,
        'sales_matrix_list': sales_matrix_list,
        'cost_matrix_list': cost_matrix_list,
    })


@login_required
def payment(request):
    today = datetime.datetime.today()
    this_year = today.strftime("%Y")
    return render(request, 'accounts/payment.html',{
        'this_year': this_year,
    })


@login_required
def payment_list(request):
    shop_label_list = [] # 納品店名リストを格納
    shop_monthly_data = {}
    delivery_total = 0

    """date__range"""
    year = request.POST.get('year')
    month = request.POST.get('month')
    month_range = calendar.monthrange(int(year),int(month))[1]
    first_date = str(year) + '-' + str(month) +'-' + '01'
    last_date = str(year) + '-' + str(month) + '-' + str(month_range)
    """Shop_label"""
    Shop_data = Shop.objects.filter(flag=1)
    for i in Shop_data:
        shop_label_list.append((i.shop_name))
        shop_label_list.sort()
    for i in range(len(shop_label_list)):
        shop_monthly_total = Cost.objects.filter(author=request.user, date__year=year, date__month=month, shop__shop_name=shop_label_list[i]).aggregate(sum=models.Sum('price'))['sum']
        if shop_monthly_total != None:
            shop_monthly_data[shop_label_list[i]] = shop_monthly_total
            delivery_total += shop_monthly_total

    return render(request, 'accounts/payment_list.html',{
        'shop_monthly_data': shop_monthly_data,
        'delivery_total': delivery_total,
    })


@login_required
def excel(request):
    today = datetime.datetime.today()
    this_year = today.strftime("%Y")
    return render(request, 'accounts/excel.html',{
        'this_year': this_year,
    })


@login_required
def excel_cost(request):
    year = request.POST.get('cost_year')
    month = request.POST.get('cost_month')
    response = setExcel.makeCostExe(request, year, month)
    return response


@login_required
def excel_delivery(request):
    year = request.POST.get('delivery_year')
    month = request.POST.get('delivery_month')
    response = setExcel.makeDeliveryExe(request, year, month)
    return response


@login_required
def excel_sales(request):
    year = request.POST.get('sales_year')
    month = request.POST.get('sales_month')
    response = setExcel.makeSalesExe(request, year, month)
    return response


@login_required
def excel_rate(request):
    year = request.POST.get('rate_year')
    month = request.POST.get('rate_month')
    response = setExcel.makeRateExe(request, year, month)
    return response


# class PostImport(LoginRequiredMixin, generic.FormView):
#     template_name = 'accounts/import.html'
#     success_url = reverse_lazy('accounts:import')
#     form_class = CSVUploadForm

#     def form_valid(self, form):
#         form.save()
#         return redirect('accounts:import')

accounts/templates/accounts/excel.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/excel.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/excel_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="form_contents">
    <div class="form_content">
        <h1 class="form_title">領収書作成</h1>
        <form action="{% url 'accounts:excel_cost' %}" method="post">
            <div class="field">
                <p>年<span class="helptext"><i class="fas fa-exclamation-circle"></i> 半角入力</p>
                <input class="form-control" type="text" size="20" name="cost_year" value="{{ this_year }}">
            </div>
            <div class="field">
                <p>月</p>
                <select name="cost_month" class="form-control">
                    <option value="01">1月</option>
                    <option value="02">2月</option>
                    <option value="03">3月</option>
                    <option value="04">4月</option>
                    <option value="05">5月</option>
                    <option value="06">6月</option>
                    <option value="07">7月</option>
                    <option value="08">8月</option>
                    <option value="09">9月</option>
                    <option value="10">10月</option>
                    <option value="11">11月</option>
                    <option value="12">12月</option>
                </select>
            </div>
            <div class="field submit_btn">
                <input type="submit" value="送信">
            </div>
            {% csrf_token %}
        </form>
    </div>
    <div class="form_content">
        <h1 class="form_title">納品書作成</h1>
        <form action="{% url 'accounts:excel_delivery' %}" method="post">
            <div class="field">
                <p>年<span class="helptext"><i class="fas fa-exclamation-circle"></i> 半角入力</p>
                <input class="form-control" type="text" size="20" name="delivery_year" value="{{ this_year }}">
            </div>
            <div class="field">
                <p>月</p>
                <select name="delivery_month" class="form-control">
                    <option value="01">1月</option>
                    <option value="02">2月</option>
                    <option value="03">3月</option>
                    <option value="04">4月</option>
                    <option value="05">5月</option>
                    <option value="06">6月</option>
                    <option value="07">7月</option>
                    <option value="08">8月</option>
                    <option value="09">9月</option>
                    <option value="10">10月</option>
                    <option value="11">11月</option>
                    <option value="12">12月</option>
                </select>
            </div>
            <div class="field submit_btn">
                <input type="submit" value="送信">
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>
<div class="form_contents">
    <div class="form_content">
        <h1 class="form_title">日報作成</h1>
        <form action="{% url 'accounts:excel_sales' %}" method="post">
            <div class="field">
                <p>年<span class="helptext"><i class="fas fa-exclamation-circle"></i> 半角入力</p>
                <input class="form-control" type="text" size="20" name="sales_year" value="{{ this_year }}">
            </div>
            <div class="field">
                <p>月</p>
                <select name="sales_month" class="form-control">
                    <option value="01">1月</option>
                    <option value="02">2月</option>
                    <option value="03">3月</option>
                    <option value="04">4月</option>
                    <option value="05">5月</option>
                    <option value="06">6月</option>
                    <option value="07">7月</option>
                    <option value="08">8月</option>
                    <option value="09">9月</option>
                    <option value="10">10月</option>
                    <option value="11">11月</option>
                    <option value="12">12月</option>
                </select>
            </div>
            <div class="field submit_btn">
                <input type="submit" value="送信">
            </div>
            {% csrf_token %}
        </form>
    </div>
    <div class="form_content">
        <h1 class="form_title">原価率作成</h1>
        <form action="{% url 'accounts:excel_rate' %}" method="post">
            <div class="field">
                <p>年<span class="helptext"><i class="fas fa-exclamation-circle"></i> 半角入力</p>
                <input class="form-control" type="text" size="20" name="rate_year" value="{{ this_year }}">
            </div>
            <div class="field">
                <p>月</p>
                <select name="rate_month" class="form-control">
                    <option value="01">1月</option>
                    <option value="02">2月</option>
                    <option value="03">3月</option>
                    <option value="04">4月</option>
                    <option value="05">5月</option>
                    <option value="06">6月</option>
                    <option value="07">7月</option>
                    <option value="08">8月</option>
                    <option value="09">9月</option>
                    <option value="10">10月</option>
                    <option value="11">11月</option>
                    <option value="12">12月</option>
                </select>
            </div>
            <div class="field submit_btn">
                <input type="submit" value="送信">
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

accounts/templates/accounts/import.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/import.css' %}">
{% endblock %}
{% block content %}
<div class="form_contents">
    <h1 class="form_title">CSVインポート</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.non_field_errors }}
        <div class="field">
            <span class="helptext"><i class="fas fa-exclamation-circle"></i> {{ form.file.help_text }}</span>
            {{ form.file }}
            {{ form.file.errors }}
        </div>
        <div class="field submit_btn">
            <button type="submit">送信</button>
        </div>
        {% csrf_token %}
    </form>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/index.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/index_rwd.css' %}">
<link rel="stylesheet" href="{% static 'css/menu.css' %}">
<link rel="stylesheet" href="{% static 'css/menu_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="content_menu">
    {% include 'menu.html' %}
    <div class="dashbord">
        <p class="dashbord_title">利益ダッシュボード ({{ this_month }}月)</p>
        <div class="dashbord_content">
            <ul>
                <li><span>利益：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ gain | intcomma }}</span></li>
                <li><span>フード原価率：</span><span class="dashbord_price">{{ food_rate | intcomma }}％</span></li>
                <li><span>ドリンク原価率：</span><span class="dashbord_price">{{ drink_rate | intcomma }}％</span></li>
            </ul>
        </div>
        <div class="form_contents">
            <div class="btn_list">
                <a class="submit_btn" href="{% url 'accounts:index' %}?param=previous&year={{ this_year }}&month={{ this_month }}"><< {{ previous_month }}月</a>
                <a class="accounts_btn" href="{% url 'accounts:index' %}?param=param&year={{ this_year }}&month={{ this_month }}">{{ this_month }}月</a>
                <a class="submit_btn" href="{% url 'accounts:index' %}?param=next&year={{ this_year }}&month={{ this_month }}">{{ next_month }}月 >></a>
            </div>
        </div>
    </div>
</div>
<div class="line_chart_content">
    <p class="line_chart_title">{{ this_year }}年度 売上・経費月別推移</p>
    <canvas id='LineChart' class="line_chart"></canvas>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
{% endblock %}
{% block script %}
<script>
    var ctx = document.getElementById("LineChart").getContext('2d');
    var DiskChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels:["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
            datasets:[
                {
                    label: "経費",
                    data:[
                    {% for yyyy_mm, total in cost_matrix_list %}
                        {{total}},
                    {% endfor %}
                    ],
                    backgroundColor: "rgba(220, 20, 60, 0.8)"
                },
                {
                    label: "売上",
                    data:[
                    {% for yyyy_mm, total in sales_matrix_list %}
                        {{total}},
                    {% endfor %}
                    ],
                    backgroundColor: "rgba(65, 105, 225, 0.8)"
                }
            ]
        },
        options: {
            responsive: true,
            scales: {
                xAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: '{{ this_year }}年'
                    },
                    ticks: {
                        maxRotation:0,
                        minRotation:0
                    },
                }],
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: '金額(円)'
                    },
                    ticks:{
                        min: 0,
                    }
                }],
            },
        }
    });
</script>
{% endblock %}

accounts/templates/accounts/payment.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/payment.css' %}">
{% endblock %}
{% block content %}
<div class="form_contents">
    <h1 class="form_title">支払いリスト作成</h1>
    <form action="{% url 'accounts:payment_list' %}" method="post">
        <div class="field">
            <p>年<span class="helptext"><i class="fas fa-exclamation-circle"></i> 半角入力</p>
            <input class="form-control" type="text" size="20" name="year" value="{{ this_year }}">
        </div>
        <div class="field">
            <p>月</p>
            <select name="month" class="form-control">
                <option value="01">1月</option>
                <option value="02">2月</option>
                <option value="03">3月</option>
                <option value="04">4月</option>
                <option value="05">5月</option>
                <option value="06">6月</option>
                <option value="07">7月</option>
                <option value="08">8月</option>
                <option value="09">9月</option>
                <option value="10">10月</option>
                <option value="11">11月</option>
                <option value="12">12月</option>
            </select>
        </div>
        <div class="field submit_btn">
            <input type="submit" value="送信">
        </div>
        {% csrf_token %}
    </form>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

accounts/templates/accounts/payment_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/payment_list.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/payment_list_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="content">
    <div class="list_contents">
        <h1 class="list_title">支払いリスト</h1>
        {% for key, value in shop_monthly_data.items %}
            <input id="{{ key }}" type="checkbox">
            <label for="{{ key }}" class="list_label">
                <i class="fas fa-store"></i> {{ key }}
                <span><i class="fas fa-yen-sign"></i> {{ value | intcomma }}</span>
            </label>
        {% endfor %}
        <p class="list_total">合計金額：<i class="fas fa-yen-sign"></i>{{ delivery_total | intcomma }}</p>
        {% comment %} <ul class="memo">
            <li><i class="fas fa-check"></i> 店名<br>銀行　支店　普通00000000</li>
            <li><i class="fas fa-check"></i> 店名<br>銀行　支店　普通00000000</li>
        </ul> {% endcomment %}
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/signup.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/signup_rwd.css' %}">
{% endblock %}
{% block content %}
<section class="common-form">
    <form method="post">
        {{ form.non_field_errors }}
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" name="username" maxlength="150" autofocus="" placeholder="ユーザー名" required="" id="id_username">
        </div>
        {{ form.username.errors }}
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-lock"></i></span>
            </div>
            <input type="password" class="form-control" name="password1" placeholder="パスワード" required="" id="id_password1">
        </div>
        {{ form.password1.error }}
        <div class="input-group form-group">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-lock"></i></span>
            </div>
            <input type="password" class="form-control" name="password2" placeholder="パスワード(再入力)" required="" id="id_password2">
        </div>
        {{ form.password2.error }}
        <div class="input-group form-group">
            <button type="submit" class="submit_btn">会員登録</button>
        </div>
        {% csrf_token %}
    </form>
</section>
{% endblock %}