cost/urls.py
from django.urls import path
from . import views


app_name = 'cost'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.CostListView.as_view(), name='cost_list'),
    path('create/', views.CostCreateView.as_view(), name='cost_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.CostUpdateView.as_view(), name='cost_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.CostDeleteView.as_view(), name='cost_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
]

kaikei/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('cost/', include('cost.urls')),
    path('sales/', include('sales.urls')),
    path('client/', include('client.urls')),
]

cost/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime


class Category(models.Model):
    class Meta:
        db_table = "category"
        verbose_name ="カテゴリ"
        verbose_name_plural ="カテゴリ"

    category_name = models.CharField(max_length=255,unique=True)

    def __str__(self):
        return self.category_name


class Shop(models.Model):
    class Meta:
        db_table = "shop"
        verbose_name ="店名"
        verbose_name_plural ="店名"

    shop_name = models.CharField(max_length=255,unique=True)
    flag = models.IntegerField(verbose_name="フラグ")
    category = models.ForeignKey(Category, on_delete = models.PROTECT, verbose_name="カテゴリ")

    def __str__(self):
        return '{0} {1}'.format(self.shop_name, self.flag)


class Cost(models.Model):
    class Meta:
        db_table = "cost"
        verbose_name ="経費"
        verbose_name_plural ="経費"

    date = models.DateField(verbose_name="日付",default=datetime.now)
    shop = models.ForeignKey(Shop, on_delete = models.PROTECT, verbose_name="店名")
    price = models.IntegerField(verbose_name="金額(税込み)", help_text="半角入力")
    memo = models.CharField(verbose_name="備考", max_length=500, blank=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="ユーザー")
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return '{0} {1} {2}'.format(self.date, self.shop, self.price)

cost/forms.py
from django import forms
from .models import Cost


class CostForm(forms.ModelForm):
    class Meta:
        model = Cost
        fields =['date', 'shop', 'price', 'memo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs['placeholder'] = field.label

cost/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.db.models import Sum
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms import CostForm
from .models import Category, Shop, Cost
import calendar
import datetime
from .lib import setDateTime, setData, setGraph


@login_required
def index(request):
    date_list = []
    past_date_list = []
    x_label = []
    monthly_total_data = []
    past_monthly_total_data = []
    matrix_list =[]
    past_matrix_list =[]

    if 'param' in request.GET:
        param = request.GET['param']
        this_year = int(request.GET['year'])
        this_month = int(request.GET['month'])
        if param == 'previous':
            this_year, this_month = setDateTime.previousMonth(this_year, this_month)
        elif param == 'next':
            this_year, this_month = setDateTime.nextMonth(this_year, this_month)
        else:
            pass
    else:
        this_year, this_month = setDateTime.nowDate()

    previous_month, next_month = setDateTime.previousAndNextMonthCreation(this_month)
    previous_year = this_year - 1

    total = setData.getTotalCost(request, this_year, this_month)
    food = setData.getCategoryCost(request, this_year, this_month, '食材')
    drink = setData.getCategoryCost(request, this_year, this_month, 'ドリンク')
    other = total - (food + drink) # その他
    cash = setData.getFlagCost(request, this_year, this_month, 0)
    cash_food = setData.getFlagCategoryCost(request, this_year, this_month, 0, '食材')
    delivery = setData.getFlagCost(request, this_year, this_month, 1)
    delivery_food = setData.getFlagCategoryCost(request, this_year, this_month, 1, '食材')

    """PieChart"""
    category_list = setData.getCategoryList()
    category_dict = setGraph.makePieChart(request, this_year, this_month, category_list, total)

    """"BarChart"""
    date_list, x_label, monthly_total_data, matrix_list = setGraph.makeBarChart(request, this_year)
    past_date_list, past_x_label, past_monthly_total_data, past_matrix_list = setGraph.makeBarChart(request, previous_year)

    """LineChart"""
    category_matrix_list, border_color, background_color = setGraph.makeLineChart(request, x_label, category_list)

    return render(request, 'cost/index.html',{
        'this_year': this_year,
        'previous_year': previous_year,
        'this_month': this_month,
        'previous_month': previous_month,
        'next_month': next_month,
        'total': total,
        'food': food,
        'drink': drink,
        'other': other,
        'cash': cash,
        'cash_food': cash_food,
        'delivery': delivery,
        'delivery_food': delivery_food,
        'category_list': category_list,
        'category_dict': category_dict,
        'matrix_list': matrix_list,
        'past_matrix_list': past_matrix_list,
        'x_label': x_label,
        'category_matrix_list': category_matrix_list,
        'border_color': border_color,
        'background_color': background_color,
    })


class CostListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Cost
    template_name = 'cost/cost_list.html'

    def queryset(self):
        if 'param' in self.request.GET:
            param = self.request.GET['param']
            this_year = int(self.request.GET['year'])
            this_month = int(self.request.GET['month'])
        return Cost.objects.filter(author=self.request.user, date__year=this_year, date__month=this_month).order_by('-pk')


class CostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Cost
    form_class = CostForm
    success_url = reverse_lazy('cost:create_done')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(CostCreateView, self).form_valid(form)

@login_required
def create_done(request):
    return render(request, 'cost/create_done.html')


class CostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Cost
    form_class = CostForm
    success_url = reverse_lazy('cost:update_done')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(CostUpdateView, self).form_valid(form)

@login_required
def update_done(request):
    return render(request, 'cost/update_done.html')


class CostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Cost
    success_url = reverse_lazy('cost:delete_done')

@login_required
def delete_done(request):
    return render(request, 'cost/delete_done.html')

cost/templates/cost/cost_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/done.css' %}">
<link rel="stylesheet" href="{% static 'css/cost/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-exclamation-triangle"></i>削除確認</h3>
        <p>{{ object }} のデータを削除していいですか？</p>
        <form method="post">
            <button class="confirm_btn">削除する</button>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

cost/templates/cost/cost_form.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/cost_form.css' %}">
<link rel="stylesheet" href="https://fengyuanchen.github.io/datepicker/css/datepicker.css">
{% endblock %}
{% block content %}
<div class="form_contents">
    <h1 class="form_title">経費入力</h1>
    <form action="" method="POST">
        {{ form.non_field_errors }}
        <div class="field">
            <p>{{ form.date.label }}</p>
            {{ form.date }}
            {{ form.date.errors }}
        </div>
        <div class="field">
            <p>{{ form.shop.label }}</p>
            {{ form.shop }}
            {{ form.shop.errors }}
        </div>
        <div class="field">
            <p>
                {{ form.price.label }}
                <span class="helptext"><i class="fas fa-exclamation-circle"></i> {{ form.price.help_text }}</span>
            </p>
            {{ form.price }}
            <!-- <p>
                <span id="tax-included"></span>
            </p> -->
            {{ form.price.errors }}
        </div>
        <div class="field">
            <p>{{ form.memo.label }}(任意)</p>
            {{ form.memo }}
            {{ form.memo.errors }}
        </div>
        <div class="field submit_btn">
            <button type="submit">送信</button>
        </div>
        {% csrf_token %}
    </form>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://fengyuanchen.github.io/datepicker/js/datepicker.js"></script>
<script src="https://fengyuanchen.github.io/datepicker/js/datepicker.ja-JP.js"></script>
{% endblock %}
{% block script %}
<script>
    $('#id_date').datepicker({
        format: 'yyyy-mm-dd',
        // language: 'ja-JP',
    });

    // $(function() {
    //     var input=$("#id_price"),tax=1.10,taxIncluded=$("#tax-included");
    //     input.on("input",function(){
    //         taxIncluded.text(Math.floor($(this).val() * tax));//税込み・切り捨て
    //     });
    // });
</script>
{% endblock %}

cost/templates/cost/cost_list.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/cost_list.css' %}">
<link rel="stylesheet" href="{% static 'css/cost/cost_list_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="rireki_contents">
    <table id=table_list>
        <thead>
            <tr>
                <th>ID <i class="fas fa-sort"></i></th>
                <th>日付 <i class="fas fa-sort"></i></th>
                <th>店名 <i class="fas fa-sort"></i></th>
                <th>金額 <i class="fas fa-sort"></i></th>
                <th>備考 <i class="fas fa-sort"></i></th>
                <th>更新・削除</th>
            </tr>
        </thead>
        <tbody>
        {% for cost in object_list %}
            <tr class="odd gradeX text-center">
                <td>{{ cost.id}}</td>
                <td>{{ cost.date}}</td>
                <td>{{ cost.shop }}</td>
                <td><i class="fas fa-yen-sign"></i> {{ cost.price }}</td>
                <td>{{ cost.memo }}</td>
                <td>
                    <a class="update_btn" href="{% url 'cost:cost_update' cost.pk %}">更新</a>
                    <a class="delete_btn" href="{% url 'cost:cost_delete' cost.pk %}">削除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
{% endblock %}
{% block script %}
<script>
    jQuery(function($){
        $.extend( $.fn.dataTable.defaults, {
            language: {
                    url: "https://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
                }
        });
        $("#table_list").DataTable({
            "searching": true,
            "paging":   false,
            "ordering": true,
            "lengthChange": false,
            // "pageLength": 25,
            "order": [[ 0, "desc" ]],
        }).columns.adjust().draw();
    });
</script>
{% endblock %}

cost/templates/cost/create_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/done.css' %}">
<link rel="stylesheet" href="{% static 'css/cost/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-server"></i>登録完了</h3>
        <p><i class="fas fa-check-double"></i>データ登録が正常終了しました。</p>
        <a href="{% url 'cost:cost_create' %}">もう一度入力</a><a href="{% url 'cost:index' %}">経費TOP</a>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

cost/templates/cost/delete_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/done.css' %}">
<link rel="stylesheet" href="{% static 'css/cost/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-server"></i>削除完了</h3>
        <p><i class="fas fa-check-double"></i>データ削除が正常終了しました。</p>
        <a href="{% url 'cost:cost_list' %}">履歴一覧へ</a><a href="{% url 'cost:index' %}">経費TOP</a>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}

cost/templates/cost/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/index.css' %}">
<link rel="stylesheet" href="{% static 'css/cost/index_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="content_menu">
    <div class="dashbord">
        <p class="dashbord_title">経費ダッシュボード ({{ this_month }}月)</p>
        <div class="dashbord_content">
            <ul>
                <li><span>経費総額：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ total | intcomma }}</span></li>
                <li><span>食材：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ food | intcomma }}</span></li>
                <li><span>ドリンク：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ drink | intcomma }}</span></li>
                <li><span>その他：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ other | intcomma }}</span></li>
                <li><span>現金仕入れ(0)：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ cash | intcomma }}</span></li>
                <li><span>現金仕入れ(食材)：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ cash_food | intcomma }}</span></li>
                <li><span>納品書(1)：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ delivery | intcomma }}</span></li>
                <li><span>業者仕入れ(食材)：</span><span class="dashbord_price"><i class="fas fa-yen-sign"></i>{{ delivery_food | intcomma }}</span></li>
            </ul>
        </div>
        <div class="form_contents">
            <div class="btn_list">
                <a class="submit_btn" href="{% url 'cost:index' %}?param=previous&year={{ this_year }}&month={{ this_month }}"><< {{ previous_month }}月</a>
                <a class="cost_btn" href="{% url 'cost:cost_list' %}?param=param&year={{ this_year }}&month={{ this_month }}">{{ this_month }}月詳細</a>
                <a class="submit_btn" href="{% url 'cost:index' %}?param=next&year={{ this_year }}&month={{ this_month }}">{{ next_month }}月 >></a>
            </div>
        </div>
    </div>
    <div class="circle_chart_content">
        <p class="circle_chart_title">{{ this_month }}月度 カテゴリ割合</p>
        <canvas id='CircleChart' class="circle_chart"></canvas>
    </div>
</div>
<div class="bar_chart_content">
    <p class="bar_chart_title">{{ this_year }}年度 経費月別推移({{ previous_year }}年度比較)</p>
    <canvas id='BarChart' class="bar_chart"></canvas>
</div>
<div class="line_chart_content">
    <p class="line_chart_title">{{ this_year }}年度 カテゴリー毎経費月別推移</p>
    <canvas id='LineChart' class="line_chart"></canvas>
</div>
<div class="new_btn">
    <a class="new_btn_link" href="{% url 'cost:cost_create' %}"><i class="fas fa-cart-arrow-down new_icon"></i></a>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
{% endblock %}
{% block script %}
<script>
    var ctx = document.getElementById('CircleChart').getContext('2d');
    var data = [[
                    {% for key, value in category_dict.items %}
                        '{{key}}',
                    {% endfor %}
                ],
                [
                    {% for key, value in category_dict.items %}
                        {{value}},
                    {% endfor %}
                ]]
    var myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: data[0],
            datasets: [{
                data: data[1],
                backgroundColor: [
                    "rgba(46, 204, 113, 0.8)",
                    "rgba(241, 196, 15, 0.8)",
                    "rgba(155, 89, 182, 0.8)",
                    "rgba(52, 73, 94, 0.8)",
                    "rgba(214, 48, 49, 0.8)",
                    "rgba(230, 126, 34, 0.8)",
                    "rgba(231, 76, 60, 0.8)",
                    "rgba(189, 195, 199, 0.8)",
                    "rgba(232, 67, 147, 0.8)",
                    "rgba(26, 188, 156, 0.8)",
                    "rgba(234,210,173, 0.8)",
                    "rgba(52, 152, 219, 0.8)",
                    "rgba(149, 165, 166, 0.8)",
                    "rgba(255, 255, 255, 0.8)"
                ],
            },]
        }
    });
</script>
<script>
    var ctx = document.getElementById("BarChart").getContext('2d');
    var DiskChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels:["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
            datasets:[
                {
                    label: "{{ previous_year }}年度",
                    data:[
                    {% for yyyy_mm, total in past_matrix_list %}
                        {{total}},
                    {% endfor %}
                    ],
                    backgroundColor: "rgba(192, 192, 192, 0.8)"
                },
                {
                    label: "{{ this_year }}年度",
                    data:[
                    {% for yyyy_mm, total in matrix_list %}
                        {{total}},
                    {% endfor %}
                    ],
                    backgroundColor: "rgba(65, 105, 225, 0.8)"
                }
            ]
        },
        options: {
            responsive: true,
            scales: {
                xAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: '{{ previous_year }}年/{{ this_year }}年'
                    },
                    ticks: {
                        maxRotation:0,
                        minRotation:0
                    },
                }],
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: '経費総額(円)'
                    },
                    ticks:{
                        min: 0,
                    }
                }],
            },
        }
    });
</script>
<script>
    var ctx = document.getElementById("LineChart").getContext('2d');
    var DiskChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: [
                {% for item in x_label %}
                    '{{item}}',
                {% endfor %}
            ],
            datasets: [
                {% for category_name in category_list %}
                    {
                        label: "{{category_name}}",
                        fill: false,
                        {% for category, color in border_color %}
                            {% if category == category_name %}
                                borderColor : "rgba({{color}})",
                            {% endif %}
                        {% endfor %}
                        {% for category, color in background_color %}
                            {% if category == category_name %}
                                backgroundColor : "rgba({{color}})",
                            {% endif %}
                        {% endfor %}
                        data: [
                            {% for time_label in x_label %}
                                {% for date, category, total in category_matrix_list %}
                                    {% if category == category_name %}
                                        {% if date == time_label %}
                                            {{total}},
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        ],
                    },
                {% endfor %}
            ]
        },
        options: {
            responsive: true,
            scales: {
                xAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: '{{ this_year }}年'
                    },
                    ticks: {
                        maxRotation:0,
                        minRotation:0
                    },
                }],
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: '合計金額(円)'
                    },
                    ticks:{
                        min: 0,
                    }
                }],
            },
        }
    });
</script>
{% endblock %}

cost/templates/cost/update_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cost/done.css' %}">
<link rel="stylesheet" href="{% static 'css/cost/done_rwd.css' %}">
{% endblock %}
{% block content %}
<div class="done_content">
    <div class="done_contents">
        <h3><i class="fas fa-server"></i>更新完了</h3>
        <p><i class="fas fa-check-double"></i>データ更新が正常終了しました。</p>
        <a href="{% url 'cost:cost_list' %}">履歴一覧へ</a><a href="{% url 'cost:index' %}">経費TOP</a>
    </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}
{% block script %}
{% endblock %}