accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('', views.index, name='index'),
    path('payment/', views.payment, name='payment'),
    path('payment_list/', views.payment_list, name='payment_list'),
    path('excel/', views.excel, name='excel'),
    path('excel_cost/', views.excel_cost, name='excel_cost'),
    path('excel_delivery/', views.excel_delivery, name='excel_delivery'),
    path('excel_sales/', views.excel_sales, name='excel_sales'),
    path('excel_rate/', views.excel_rate, name='excel_rate'),
    # path('import/', views.PostImport.as_view(), name='import'),
]

client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    # path('', views.index, name='index'),
    path('list/', views.ClientListView.as_view(), name='client_list'),
    path('detail/<int:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('create/', views.ClientCreateView.as_view(), name='client_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('create_visit/<int:pk>/', views.create_visit, name='create_visit'),
    path('update/<int:pk>/', views.ClientUpdateView.as_view(), name='client_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('update_visit/<int:pk>/', views.update_visit, name='update_visit'),
    path('delete/<int:pk>/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
    path('delete_visit/<int:pk>/', views.delete_visit, name='delete_visit'),
]

cost/urls.py
from django.urls import path
from . import views


app_name = 'cost'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.CostListView.as_view(), name='cost_list'),
    path('create/', views.CostCreateView.as_view(), name='cost_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.CostUpdateView.as_view(), name='cost_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.CostDeleteView.as_view(), name='cost_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
]

kaikei/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('cost/', include('cost.urls')),
    path('sales/', include('sales.urls')),
    path('client/', include('client.urls')),
]

sales/urls.py
from django.urls import path
from . import views


app_name = 'sales'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.SalesListView.as_view(), name='sales_list'),
    path('create/', views.SalesCreateView.as_view(), name='sales_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.SalesUpdateView.as_view(), name='sales_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.SalesDeleteView.as_view(), name='sales_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/base_rwd.css' %}">
    {% block extra_css %}{% endblock %}
    <title>会計管理</title>
</head>
<body>
    <div class="container">
        <header class="header">
            <div class="header_left">
                {% if user.is_authenticated %}
                <p class="logo"><a href="{% url 'accounts:index' %}">{{user.username}}様</a></p>
                {% else %}
                <p class="logo"><a href="">会計管理</a></p>
                {% endif %}
            </div>
            <div class="header_right">
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:index' %}">利益</a></li>
                    <li><a href="{% url 'cost:index' %}">経費</a></li>
                    <li><a href="{% url 'sales:index' %}">売上</a></li>
                    <li><a href="{% url 'accounts:payment' %}">支払い</a></li>
                    <li><a href="{% url 'client:client_list' %}">顧客情報</a></li>
                    <li><a href="{% url 'accounts:excel' %}">EXCEL</a></li>
                    <li><a href="{% url 'logout' %}" class="logout">ログアウト</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:signup' %}" class="signup">会員登録</a></li>
                    <li><a href="{% url 'login' %}" class="login">ログイン</a></li>
                    {% endif %}
                </ul>
            </div>
        </header>
        <header class="rwd_header">
            <div id="nav-drawer">
                <input id="nav-input" type="checkbox" class="nav-unshown">
                <label id="nav-open" for="nav-input"><i class="fas fa-bars"></i></label>
                <label class="nav-unshown" id="nav-close" for="nav-input"></label>
                <div id="nav-content">
                    <div class="header_left">
                        <ul>
                            <li class="nav_menu">メニュー</li>
                            {% if user.is_authenticated %}
                            <li><i class="fas fa-chart-line"></i> 利益<a href="{% url 'accounts:index' %}"></a></li>
                            <li><i class="fas fa-cart-arrow-down"></i> 経費<a href="{% url 'cost:index' %}"></a></li>
                            <li><i class="fas fa-comment-dollar"></i> 売上<a href="{% url 'sales:index' %}"></a></li>
                            <li><i class="fas fa-university"></i> 支払い<a href="{% url 'accounts:payment' %}"></a></li>
                            <li><i class="fas fa-user-circle"></i> 顧客情報<a href="{% url 'client:client_list' %}"></a></li>
                            <li><i class="far fa-file-excel"></i> EXCEL<a href="{% url 'accounts:excel' %}"></a></li>
                            <li><i class="fas fa-sign-out-alt"></i> ログアウト<a href="{% url 'logout' %}"></a></li>
                            {% else %}
                            <li><i class="fas fa-user-plus"></i> 会員登録<a href="{% url 'accounts:signup' %}"></a></li>
                            <li><i class="fas fa-sign-in-alt"></i> ログイン<a href="{% url 'login' %}"</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="header_right">
                {% if user.is_authenticated %}
                <p class="logo"><a href="{% url 'accounts:index' %}">{{user.username}}様</a></p>
                {% else %}
                <p class="logo"><a href="">会計管理</a></p>
                {% endif %}
            </div>
        </header>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
        <footer class="footer">
            <p>©️ 2020 会計管理 All Rights Reserved.</p>
        </footer>
    </div>
    {% block extra_js %}{% endblock %}
    {% block script %}{% endblock %}
</body>
</html>

templates/menu.html
<div class="menus">
    <div class="menus_up">
        <div class="menu cost">
            <span class="icon"><i class="fas fa-cart-arrow-down"></i></span>
            <br>
            <p>経費詳細</p>
            <a href="{% url 'cost:index' %}"></a>
        </div>
        <div class="menu sales">
            <span class="icon"><i class="fas fa-comment-dollar"></i></span>
            <br>
            <p>売上詳細</p>
            <a href="{% url 'sales:index' %}"></a>
        </div>
    </div>
    <div class="menus_down">
        <div class="menu payment">
            <span class="icon"><i class="fas fa-university"></i></span>
            <br>
            <p>支払リスト作成</p>
            <a class="" href="{% url 'accounts:payment' %}"></a>
        </div>
        <div class="menu client">
            <span class="icon"><i class="fas fa-user-circle"></i></span>
            <br>
            <p>顧客情報</p>
            <a class="" href="{% url 'client:client_list' %}"></a>
        </div>
    </div>
</div>